// <auto-generated />
using System;
using BackEnd_Thaibev.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackEnd_Thaibev.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackEnd_Thaibev.Models.TbMMsg", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("msg_code")
                        .HasColumnType("text");

                    b.Property<string>("msg_desc")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("tb_m_msg");
                });

            modelBuilder.Entity("BackEnd_Thaibev.Models.TbTChoiceItems", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("choice_text")
                        .HasColumnType("text");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("is_correct")
                        .HasColumnType("text");

                    b.Property<int?>("ref_question_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("tb_t_choice_items");
                });

            modelBuilder.Entity("BackEnd_Thaibev.Models.TbTQuestion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("answer")
                        .HasColumnType("text");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("question")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("tb_t_question");
                });
#pragma warning restore 612, 618
        }
    }
}
